# Generated by Django 5.2.6 on 2025-10-19 00:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='isbn',
        ),
        migrations.AddField(
            model_name='textbook',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textbook',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('worn', 'Worn'), ('other', 'Other')], default='used', max_length=20),
        ),
        migrations.AddField(
            model_name='textbook',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textbook',
            name='edition',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='textbook',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='base.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbook',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
